import { BadRequestException, ConflictException, ForbiddenException, Injectable, NotFoundException, UnprocessableEntityException } from '@nestjs/common';
import { Prisma } from '@prisma/client';
import { randomUUID } from 'node:crypto';
import { PrismaService } from '../database/prisma.service';
import { recordInventoryLedger } from '../inventory/inventory-ledger';
import { assertFifoStockInvariant } from '../inventory/fifo';
import { PostPurchaseReceiptDto, PurchaseReceiptQueryDto, SettleShortageDto } from './dto/purchase-receipt.dto';

const managerPermissions = ['backoffice.view', 'company.manage'];
const receiptInclude = Prisma.validator<Prisma.PurchaseReceiptInclude>()({
  location: { select: { id: true, name: true, code: true } }, importedBy: { select: { id: true, name: true } }, approvedBy: { select: { id: true, name: true } },
  batches: { include: { product: { select: { id: true, sku: true, name: true, fifoEnabledAt: true } }, uom: { select: { id: true, code: true, name: true, conversionFactor: true } }, events: { orderBy: { createdAt: 'asc' } }, saleAllocations: { include: { saleItem: { include: { sale: { select: { receiptNo: true, completedAt: true } } } } }, orderBy: { createdAt: 'asc' } } }, orderBy: [{ receivedAt: 'asc' }, { createdAt: 'asc' }, { displayBatchId: 'asc' }] },
});
type ReceiptRecord = Prisma.PurchaseReceiptGetPayload<{ include: typeof receiptInclude }>;

@Injectable()
export class PurchaseReceiptService {
  constructor(private readonly db: PrismaService) {}

  async list(input: PurchaseReceiptQueryDto) { await this.assertManager(input); const rows = await this.db.purchaseReceipt.findMany({ where: { companyId: input.companyId }, include: receiptInclude, orderBy: { createdAt: 'desc' }, take: 100 }); return Promise.all(rows.map((row) => this.view(row))); }
  async get(id: string, input: PurchaseReceiptQueryDto) { await this.assertManager(input); const row = await this.db.purchaseReceipt.findFirst({ where: { id, companyId: input.companyId }, include: receiptInclude }); if (!row) throw new NotFoundException('Purchase receipt was not found'); return this.view(row); }

  async post(id: string, input: PostPurchaseReceiptDto) {
    const actor = await this.assertManager(input); if (!input.confirmed) throw new BadRequestException('Explicit manager confirmation is required before posting inventory'); if (input.managerId !== actor.id) throw new ForbiddenException('The approving manager must match the authenticated manager');
    try {
      await this.db.$transaction(async (tx) => {
        const locked = await tx.$queryRaw<Array<{ status: string }>>(Prisma.sql`SELECT "status" FROM "PurchaseReceipt" WHERE "id"=${id} AND "companyId"=${input.companyId} FOR UPDATE`); if (!locked[0]) throw new NotFoundException('Purchase receipt was not found'); if (locked[0].status === 'POSTED') return; if (locked[0].status !== 'DRAFT') throw new ConflictException(`Purchase receipt status ${locked[0].status} cannot be posted`);
        const receipt = await tx.purchaseReceipt.findUnique({ where: { id }, include: { batches: { include: { product: true } } } }); if (!receipt || !receipt.batches.length) throw new UnprocessableEntityException('Purchase receipt has no draft inventory batches');
        const prepared = [];
        for (const batch of receipt.batches) {
          if (batch.status !== 'DRAFT') throw new ConflictException(`Inventory batch ${batch.displayBatchId} is not a draft`);
          if (batch.finalUnitCost == null || batch.totalBatchValue == null || batch.purchaseUnitCost == null) throw new UnprocessableEntityException(`Inventory batch ${batch.displayBatchId} is missing an approved purchase cost`);
          const snapshots = await tx.$queryRaw<Array<{ quantity: Prisma.Decimal }>>(Prisma.sql`SELECT "quantity" FROM "StockSnapshot" WHERE "locationId"=${batch.locationId} AND "productId"=${batch.productId} FOR UPDATE`); const beforeQuantity = snapshots[0]?.quantity ?? new Prisma.Decimal(0); prepared.push({ batch, beforeQuantity, afterQuantity: beforeQuantity.add(batch.receivedQuantity) });
        }
        if (prepared.some((row) => row.beforeQuantity.isNegative()) && !input.negativeStockAcknowledged) throw new UnprocessableEntityException('Manager acknowledgement is required because current stock is negative. Posting does not settle or recost the shortage automatically');
        const postedAt = new Date();
        for (const row of prepared) {
          const { batch, beforeQuantity, afterQuantity } = row; const totalBatchValue = batch.totalBatchValue!; const finalUnitCost = batch.finalUnitCost!; const purchaseUnitCost = batch.purchaseUnitCost!; const priorLedger = await tx.inventoryLedgerEntry.findFirst({ where: { companyId: input.companyId, locationId: batch.locationId, productId: batch.productId }, orderBy: [{ createdAt: 'desc' }, { id: 'desc' }] }); const runningValue = priorLedger?.runningValue == null ? null : priorLedger.runningValue.add(totalBatchValue);
          await tx.stockSnapshot.upsert({ where: { locationId_productId: { locationId: batch.locationId, productId: batch.productId } }, update: { quantity: afterQuantity, capturedAt: postedAt }, create: { locationId: batch.locationId, productId: batch.productId, quantity: afterQuantity, capturedAt: postedAt } });
          await tx.inventoryBatch.update({ where: { id: batch.id }, data: { status: 'POSTED', remainingQuantity: batch.receivedQuantity, approvedById: actor.id, postedAt } });
          await tx.inventoryBatchEvent.create({ data: { id: randomUUID(), companyId: input.companyId, inventoryBatchId: batch.id, type: 'POSTED', quantityDelta: batch.receivedQuantity, beforeRemaining: 0, afterRemaining: batch.receivedQuantity, actorId: receipt.importedById, approvedById: actor.id, reason: `Approved Bukku purchase bill ${receipt.bukkuReference}`, referenceType: 'PURCHASE_RECEIPT', referenceId: receipt.id, createdAt: postedAt } });
          await recordInventoryLedger(tx, { companyId: input.companyId, locationId: batch.locationId, productId: batch.productId, actorId: receipt.importedById, approvedById: actor.id, uomId: batch.uomId, type: 'ADJUSTMENT', sourceType: 'BUKKU_PURCHASE', quantityDelta: batch.receivedQuantity, unitCost: finalUnitCost, valueDelta: totalBatchValue, runningQuantity: afterQuantity, runningValue, averageUnitCost: null, costStatus: 'FINAL', referenceType: 'FIFO_PURCHASE_BATCH', referenceId: batch.id, reason: `Bukku bill ${receipt.bukkuReference}; supplier ${receipt.supplier}`, createdAt: postedAt });
          const legacyDrafts = await tx.inventoryBatch.count({ where: { productId: batch.productId, locationId: batch.locationId, status: 'DRAFT', sourceType: 'OPENING_LEGACY' } }); if (!legacyDrafts && !batch.product.fifoEnabledAt) await tx.product.update({ where: { id: batch.productId }, data: { fifoEnabledAt: postedAt, lastPurchasedAt: postedAt } }); else await tx.product.update({ where: { id: batch.productId }, data: { lastPurchasedAt: postedAt } });
          await assertFifoStockInvariant(tx, { companyId: input.companyId, locationId: batch.locationId, productId: batch.productId });
          await tx.productPurchasePrice.upsert({ where: { productId_uomId: { productId: batch.productId, uomId: batch.uomId } }, update: { amount: purchaseUnitCost }, create: { productId: batch.productId, uomId: batch.uomId, amount: purchaseUnitCost } });
        }
        await tx.purchaseReceipt.update({ where: { id }, data: { status: 'POSTED', approvedById: actor.id, negativeStockAcknowledged: prepared.some((row) => row.beforeQuantity.isNegative()), postedAt } });
        await tx.auditLog.create({ data: { companyId: input.companyId, actorId: actor.id, action: 'FIFO_PURCHASE_RECEIPT_POSTED', entityType: 'PurchaseReceipt', entityId: id, reason: `Posted Bukku bill ${receipt.bukkuReference}`, metadata: { importingUserId: receipt.importedById, approvingManagerId: actor.id, supplier: receipt.supplier, bukkuReference: receipt.bukkuReference, negativeStockAcknowledged: prepared.some((row) => row.beforeQuantity.isNegative()) }, after: { postedAt: postedAt.toISOString(), batches: prepared.map(({ batch, beforeQuantity, afterQuantity }) => ({ batchId: batch.displayBatchId, productId: batch.productId, receivedQuantity: batch.receivedQuantity.toFixed(4), finalUnitCost: batch.finalUnitCost!.toFixed(4), beforeQuantity: beforeQuantity.toFixed(4), afterQuantity: afterQuantity.toFixed(4) })) } } });
      }, { isolationLevel: Prisma.TransactionIsolationLevel.Serializable });
    } catch (error) { if (error instanceof BadRequestException || error instanceof ForbiddenException || error instanceof NotFoundException || error instanceof ConflictException || error instanceof UnprocessableEntityException) throw error; if (error instanceof Prisma.PrismaClientKnownRequestError && error.code === 'P2034') throw new ConflictException('Inventory changed while posting. Review the receipt again'); throw error; }
    return this.get(id, input);
  }

  async enableLegacyFifo(productId: string, input: PostPurchaseReceiptDto) {
    const actor = await this.assertManager(input); if (!input.confirmed || input.managerId !== actor.id) throw new ForbiddenException('Manager confirmation is required to enable FIFO for legacy stock');
    await this.db.$transaction(async (tx) => {
      const product = await tx.product.findFirst({ where: { id: productId, companyId: input.companyId } }); if (!product) throw new NotFoundException('Product was not found');
      const batches = await tx.inventoryBatch.findMany({ where: { productId, companyId: input.companyId, sourceType: 'OPENING_LEGACY', status: 'DRAFT' } });
      if (!batches.length) throw new BadRequestException('No legacy opening-stock batches require review'); const unvalued = batches.filter((batch) => batch.finalUnitCost == null || (batch.finalUnitCost.isZero() && !batch.receivedQuantity.isZero())); if (unvalued.length) throw new UnprocessableEntityException('Value the legacy opening batches through an approved cost-adjustment workflow before enabling FIFO');
      const approvedAt = new Date(); for (const batch of batches) { await tx.inventoryBatch.update({ where: { id: batch.id }, data: { status: batch.remainingQuantity.isZero() ? 'FULLY_CONSUMED' : 'POSTED', approvedById: actor.id, postedAt: approvedAt } }); await tx.inventoryBatchEvent.create({ data: { id: randomUUID(), companyId: input.companyId, inventoryBatchId: batch.id, type: 'LEGACY_APPROVED', quantityDelta: 0, beforeRemaining: batch.remainingQuantity, afterRemaining: batch.remainingQuantity, actorId: actor.id, approvedById: actor.id, reason: 'Manager reviewed legacy opening stock before FIFO enablement', referenceType: 'PRODUCT_FIFO_ENABLE', referenceId: productId } }); }
      await tx.product.update({ where: { id: productId }, data: { fifoEnabledAt: approvedAt } });
      for (const locationId of [...new Set(batches.map((batch) => batch.locationId))]) await assertFifoStockInvariant(tx, { companyId: input.companyId, locationId, productId });
      await tx.auditLog.create({ data: { companyId: input.companyId, actorId: actor.id, action: 'PRODUCT_FIFO_ENABLED', entityType: 'Product', entityId: productId, reason: 'Manager reviewed legacy opening-stock batches', after: { approvedAt, batchIds: batches.map((batch) => batch.displayBatchId) } } });
    }); return { productId, fifoEnabled: true };
  }

  async productBatches(productId: string, input: PurchaseReceiptQueryDto) { await this.assertManager(input); const product = await this.db.product.findFirst({ where: { id: productId, companyId: input.companyId }, select: { id: true, sku: true, name: true, fifoEnabledAt: true } }); if (!product) throw new NotFoundException('Product was not found'); const batches = await this.db.inventoryBatch.findMany({ where: { companyId: input.companyId, productId }, include: { location: { select: { id: true, name: true } }, events: { orderBy: { createdAt: 'desc' } }, saleAllocations: { include: { saleItem: { include: { sale: { select: { receiptNo: true, completedAt: true } } } } }, orderBy: { createdAt: 'desc' } } }, orderBy: [{ receivedAt: 'asc' }, { createdAt: 'asc' }, { displayBatchId: 'asc' }] }); return { product, stockOnHand: batches.reduce((sum, batch) => sum + Number(batch.remainingQuantity), 0), fifoInventoryValue: batches.reduce((sum, batch) => sum + (batch.finalUnitCost == null ? 0 : Number(batch.remainingQuantity.mul(batch.finalUnitCost))), 0), oldestActiveBatch: batches.find((batch) => batch.status === 'POSTED' && batch.remainingQuantity.greaterThan(0))?.displayBatchId ?? null, lastPurchaseCost: [...batches].reverse().find((batch) => batch.sourceType === 'BUKKU_PURCHASE' && batch.purchaseUnitCost != null)?.purchaseUnitCost ?? null, latestBukkuReference: [...batches].reverse().find((batch) => batch.bukkuReference)?.bukkuReference ?? null, batches };
  }

  async shortages(input: PurchaseReceiptQueryDto) { await this.assertManager(input); return this.db.inventoryBatch.findMany({ where: { companyId: input.companyId, status: 'SHORTAGE', remainingQuantity: { lt: 0 } }, include: { product: { select: { sku: true, name: true } }, location: { select: { name: true } }, saleAllocations: { include: { saleItem: { include: { sale: { select: { receiptNo: true, completedAt: true } } } } } } }, orderBy: { receivedAt: 'asc' } }); }

  async settleShortage(shortageBatchId: string, input: SettleShortageDto) {
    const actor = await this.assertManager(input); if (!input.confirmed || input.managerId !== actor.id) throw new ForbiddenException('Manager confirmation is required to settle a shortage');
    await this.db.$transaction(async (tx) => { const rows = await tx.$queryRaw<Array<{ id: string }>>(Prisma.sql`SELECT "id" FROM "InventoryBatch" WHERE "id" IN (${Prisma.join([shortageBatchId, input.targetBatchId])}) FOR UPDATE`); if (rows.length !== 2) throw new NotFoundException('Shortage or target FIFO batch was not found'); const shortage = await tx.inventoryBatch.findFirst({ where: { id: shortageBatchId, companyId: input.companyId, status: 'SHORTAGE' } }); const target = await tx.inventoryBatch.findFirst({ where: { id: input.targetBatchId, companyId: input.companyId, status: 'POSTED' } }); if (!shortage || !target || shortage.productId !== target.productId || shortage.locationId !== target.locationId) throw new BadRequestException('Choose a posted batch for the same product and location'); const quantity = new Prisma.Decimal(input.quantity); if (quantity.greaterThan(shortage.remainingQuantity.abs()) || quantity.greaterThan(target.remainingQuantity)) throw new UnprocessableEntityException('Settlement quantity exceeds the shortage or target batch balance'); const shortageAfter = shortage.remainingQuantity.add(quantity); const targetAfter = target.remainingQuantity.sub(quantity); const now = new Date(); await tx.inventoryBatch.update({ where: { id: shortage.id }, data: { remainingQuantity: shortageAfter, status: shortageAfter.isZero() ? 'FULLY_CONSUMED' : 'SHORTAGE' } }); await tx.inventoryBatch.update({ where: { id: target.id }, data: { remainingQuantity: targetAfter, status: targetAfter.isZero() ? 'FULLY_CONSUMED' : 'POSTED' } }); await tx.inventoryBatchEvent.createMany({ data: [{ id: randomUUID(), companyId: input.companyId, inventoryBatchId: shortage.id, type: 'SHORTAGE_SETTLED', quantityDelta: quantity, beforeRemaining: shortage.remainingQuantity, afterRemaining: shortageAfter, actorId: actor.id, approvedById: actor.id, reason: input.reason, referenceType: 'SHORTAGE_SETTLEMENT', referenceId: `${shortage.id}:${target.id}`, createdAt: now }, { id: randomUUID(), companyId: input.companyId, inventoryBatchId: target.id, type: 'SHORTAGE_SETTLEMENT_SOURCE', quantityDelta: quantity.negated(), beforeRemaining: target.remainingQuantity, afterRemaining: targetAfter, actorId: actor.id, approvedById: actor.id, reason: input.reason, referenceType: 'SHORTAGE_SETTLEMENT', referenceId: `${shortage.id}:${target.id}`, createdAt: now }] }); await tx.auditLog.create({ data: { companyId: input.companyId, actorId: actor.id, action: 'FIFO_SHORTAGE_SETTLED', entityType: 'InventoryBatch', entityId: shortage.id, reason: input.reason, before: { shortageRemaining: shortage.remainingQuantity.toFixed(4), targetRemaining: target.remainingQuantity.toFixed(4) }, after: { quantity: quantity.toFixed(4), shortageRemaining: shortageAfter.toFixed(4), targetBatchId: target.id, targetRemaining: targetAfter.toFixed(4) } } }); }, { isolationLevel: Prisma.TransactionIsolationLevel.Serializable }); return { shortageBatchId, settled: input.quantity };
  }

  private async view(receipt: ReceiptRecord) {
    const productIds = [...new Set(receipt.batches.map((batch) => batch.productId))];
    const locationIds = [...new Set(receipt.batches.map((batch) => batch.locationId))];
    const snapshots = productIds.length && locationIds.length
      ? await this.db.stockSnapshot.findMany({ where: { productId: { in: productIds }, locationId: { in: locationIds } }, select: { productId: true, locationId: true, quantity: true } })
      : [];
    const snapshotByProductLocation = new Map(snapshots.map((snapshot) => [`${snapshot.locationId}:${snapshot.productId}`, snapshot.quantity]));
    return { id: receipt.id, bukkuReference: receipt.bukkuReference, supplier: receipt.supplier, purchaseDate: receipt.purchaseDate, status: receipt.status, location: receipt.location, sourceFileName: receipt.sourceFileName, batchId: receipt.batchId, importedBy: receipt.importedBy, approvedBy: receipt.approvedBy, negativeStockAcknowledged: receipt.negativeStockAcknowledged, createdAt: receipt.createdAt, postedAt: receipt.postedAt, hasNegativeStock: receipt.batches.some((batch) => (snapshotByProductLocation.get(`${batch.locationId}:${batch.productId}`) ?? new Prisma.Decimal(0)).isNegative()), batches: receipt.batches.map((batch) => ({ id: batch.id, displayBatchId: batch.displayBatchId, sku: batch.product.sku, productName: batch.product.name, unit: batch.uom.code, receivedQuantity: Number(batch.receivedQuantity), remainingQuantity: Number(batch.remainingQuantity), purchaseUnitCost: batch.purchaseUnitCost == null ? null : Number(batch.purchaseUnitCost), landedCostPerUnit: Number(batch.landedCostPerUnit), finalUnitCost: batch.finalUnitCost == null ? null : Number(batch.finalUnitCost), totalBatchValue: batch.totalBatchValue == null ? null : Number(batch.totalBatchValue), billDate: batch.billDate, receivedAt: batch.receivedAt, status: batch.status, fifoEnabled: Boolean(batch.product.fifoEnabledAt), events: batch.events, allocations: batch.saleAllocations.map((allocation) => ({ receiptNo: allocation.saleItem.sale.receiptNo, saleLineId: allocation.saleItemId, quantity: Number(allocation.quantity), unitCost: allocation.unitCost == null ? null : Number(allocation.unitCost), cogs: allocation.cogs == null ? null : Number(allocation.cogs), type: allocation.type, createdAt: allocation.createdAt })) })) };
  }
  private async assertManager(input: PurchaseReceiptQueryDto) { const actor = await this.db.user.findFirst({ where: { id: input.actorId, companyId: input.companyId, status: 'ACTIVE' }, include: { role: true } }); const permissions = Array.isArray(actor?.role.permissions) ? actor.role.permissions.filter((permission): permission is string => typeof permission === 'string') : []; if (!actor || !managerPermissions.some((permission) => permissions.includes(permission))) throw new ForbiddenException('Manager access is required for purchase receipts and FIFO inventory'); return { id: actor.id, permissions }; }
}
